##
# Jump App Microservices Chart values
#
# DEV environment
#
##

# Subcharts status
jump-app-cicd:
  enabled: false
jump-app-argocd:
  enabled: false
jump-app-ocp-bootstrap:
  enabled: false
jump-app-micros:
  enabled: true
  istio:
    enabled: true
    namespace: istio-system
    mtls: true
  knative:
    enabled: true
  cicd:
    namespace: jump-app-cicd
  grpc:
    enabled: true
    ssl: false

# Global variables
global:
  appsDomain: apps.acidonpe88.sandbox2776.opentlc.com
  apps:
    front-javascript:
      imagerepo: quay.io/acidonpe/jump-app-front-javascript-grpc
      imagetag: latest
      replicas: 1
      envVars:
        APP_REF_NAME: jump-app
      containerPorts:
        http:
          containerPort: 3000
          protocol: TCP
      servicePorts:
        http-8080:
          port: 8080
          protocol: TCP
          targetPort: 3000
      public: true
      routeTargetPort: http-8080
      backend: back-golang
    back-golang:
      imagerepo: quay.io/acidonpe/jump-app-back-golang-grpc
      imagetag: latest
      replicas: 1
      envVars:
        APP_REF_NAME: jump-app
      containerPorts:
        http:
          containerPort: 50051
          protocol: TCP
      servicePorts:
        tcp-50051:
          port: 50051
          protocol: TCP
          targetPort: 50051
      public: true
      routeTargetPort: tcp-50051
      frontSettings:
        var: REACT_APP_GOLANG
        port: 50051
    back-python:
      imagerepo: quay.io/acidonpe/jump-app-back-python-grpc
      imagetag: latest
      replicas: 1
      envVars:
        APP_REF_NAME: jump-app
        PYTHONPATH: ./grpcserver
      containerPorts:
        http:
          containerPort: 50052
          protocol: TCP
      servicePorts:
        tcp-50052:
          port: 50052
          protocol: TCP
          targetPort: 50052
      public: false
      routeTargetPort: http-8444
      frontSettings:
        var: REACT_APP_PYTHON
        port: 50052
    back-springboot:
      imagerepo: quay.io/acidonpe/jump-app-back-springboot-grpc
      imagetag: latest
      replicas: 1
      envVars:
        APP_REF_NAME: jump-app
      containerPorts:
        http:
          containerPort: 50053
          protocol: TCP
      servicePorts:
        tcp-50053:
          port: 50053
          protocol: TCP
          targetPort: 50053
      public: false
      routeTargetPort: http-8443
      frontSettings:
        var: REACT_APP_SPRINGBOOT
        port: 50053
