apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  namespace: istio-system
  name: basic
spec:
  runtime:
    components:
      pilot:
        deployment:
          replicas: 1
  tracing:
    sampling: 10000
    type: Jaeger
  gateways:
    enabled: true
    egress:
      enabled: true
      runtime:
        deployment:
          replicas: 1
    ingress:
      enabled: true
      runtime:
        deployment:
          replicas: 1
    openshiftRoute:
      enabled: false
  policy:
    type: Istiod
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: true
  version: v2.5
  telemetry:
    type: Istiod
